config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bands#home"
  resources :users do
    resources :bookings, only: [:index]
  end
  resources :bands do
    resources :reviews, only: [:new, :create]
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  # belongs_to :user
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :band
  belongs_to :venue
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :band

  validates :content, presence: true
  validates :rating, inclusion: { in: 1..5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :bands, through: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  before_action :set_band, only: [:show]

  def home
    @bands = Band.all
  end

  def index
    @genres = Band.pluck(:genre).uniq
    @selected_genre = params[:genre]
      if params[:query].present?
     sql_subquery = "genre ILIKE :query OR name ILIKE :query"
    @bands = Band.where(sql_subquery, query: "%#{params[:query]}%")
      elsif  @selected_genre.present?
        @bands = Band.where(genre: @selected_genre)
      else
        @bands = Band.all
      end
  end

  def show
    @booking = Booking.new(band_id: @band)
    @reviews = Review.where(band: @band)
    @review = Review.new(band: @band)
    @bookings = Booking.where(band: @band)
    @venues = Venue.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_path(@band)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def band_params
    params.require(:band).permit(:name, :genre, :price_per_night, :image_url)
  end

  def set_band
    @band = Band.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.band = Band.find(params[:band_id])
    @booking.user = current_user
    # @booking.venue = Venue.find(params[:venue_id])
    price = calculate_total_price(@booking.start_date, @booking.end_date, @booking.band.price_per_night)
    @booking.total_price = price
    if @booking.save
      redirect_to user_bookings_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :venue_id)
  end
end

# calculation isn't quite working yet, needs to be looked at

def calculate_total_price(start_date, end_date, price_per_night)
  if start_date == end_date
    @booking.band.price_per_night
  else
    number_of_nights = (end_date.to_date - start_date.to_date).to_i
    number_of_nights >= 0 ? (number_of_nights * price_per_night) + price_per_night : 0
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @band = Band.find(params[:band_id])
    @review = Review.new(review_params)
    @review.band = @band
    if @review.save
      redirect_to band_path(@band)
    else
      render "bands/show", status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/home.html.erb
<%= render 'shared/banner' %>

app/views/bands/index.html.erb
<div class="current-banner">
  <div class="reused-banner-inner">
<h1>Current Listings</h1>

  </div>
  <hr>
</div>
<hr>
<div class="container">

<% if @bands.empty? %>
    <div class="text-center">
    <h2>Sorry, there are no results for your query <i class="fa-regular fa-face-kiss-beam"></i></h2>
    <hr>
    <%= link_to "Browse Listings", bands_path, class: 'btn btn-primary' %>
    </div>
  <% else %>

<div style="text-align:right;margin-top: 16px;margin-bottom: 16px;" class="mt-50">
<%= form_tag bands_path, class: "p-50", method: :get do %>
  <%= select_tag :genre, options_for_select([["All", ""]] + @genres.map { |genre| [genre, genre] }, selected: @selected_genre), include_blank: true %>
  <%= submit_tag 'Filter by genre', class: "btn btn-secondary btn-sm ml-15" %>
<% end %>
</div>

    <div class="flex-item cards">
      <% @bands.each do |band| %>
        <div class="card-product shadow border">
          <%= image_tag band.image_url %>
          <div class="ml-5 mr-50px d-flex flex-fill justify-content-evenly">
            <div class="p-2 card-product-infos">
              <h2><%= band.name %></h2>
              <p class="p-2 card-product-infos text-center">£<%= band.price_per_night %></p>
            </div>
            <div class="d-flex flex-column justify-content-center text-center">
              <%= link_to band_path(band), class: "p-2" do %>
              <button type="button" class="btn btn-outline-secondary p-2">View</button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
       <% end %>
  </div>
</div>
<%#
    <div class="col-6">
          <div id='map' style='width: 400px; height: 80%;'></div>
    </div>
  </div>
</div> %>

app/views/bands/new.html.erb
<!-- Render Navbar Here -->
<%= render 'navbar' %>
<div class="container">
  <h1 class="text-center">Create Your Band Profile</h1>
</div>

<!-- Render Footer Here -->

app/views/bands/show.html.erb
<div class="reused-banner">
  <div class="reused-banner-inner">
      <div class="band-info-head d-flex">
        <div class="band-image-show">
          <img src="<%= @band.image_url%>" alt="Photo of <%= @band.name %>">
        </div>
        <div class="band-name-show col-sm-6">
          <h1><%= @band.name%></h1>
          <h5>Genre: <%= @band.genre.capitalize %></h5>
          <h5>Price per night: £<%= @band.price_per_night%></h5>
        </div>
      </div>
  </div>
</div>

<div class="container" style="margin-bottom:50px;">
  <hr>

  <div class="row">
    <div class="col-6">
      <h5>REVIEWS</h5>
      <% if @reviews.empty?%>
        <h5 class="text-center">There are no reviews</h5>
      <% else %>
        <% @reviews.each do |review| %>
          <div class="card shadow" id="review-card">
            <ul class="list-group list-group-horizontal-md mx-2">
              <% review.rating.times do %>
                <li><i class="fa-regular fa-star"></i></li>
              <% end %>
            </ul>
            <p class="mx-2"><em>"<%= review.content %>"</em></p>
          </div>
        <% end %>
      <% end %>
      <div class="review-form shadow">
        <%= simple_form_for @review, {url: band_reviews_path(@band)} do |f| %>
          <%= f.input :content, label: "Leave a Review:", placeholder: 'Write your review here ...' %>
          <%= f.input :rating, input_html: {min: 0, max: 5, step: 1} %>
          <p class="text-center"><%= f.submit%></p>
        <% end %>
      </div>
      <hr>
      <div class="p-2 text-center">
          <h5>BAND INFO AND LINKS</h5>
          <div class="logo-dispay">
            <i class="fa-brands fa-facebook"></i>
            <i class="fa-brands fa-instagram"></i>
            <i class="fa-brands fa-soundcloud"></i>
          </div>
      </div>
      <hr>
    </div>
    <div class="col-6 shadow p-1">
      <div class="p-2">
        <h3 class="text-center">BOOK NOW</h3>
        <%= simple_form_for [@band, @booking] do |f| %>
          <%= f.input :start_date, as: :date %>
          <%= f.input :end_date, as: :date %>
          <%= f.association :venue, collection: Venue.all %>
          <p class="text-center"><%= f.submit 'Book', class: 'btn btn-primary' %></p>
        <% end %>
        <hr>
      </div>
      <div class="p-1 text-center">
        <h3>UPCOMING SHOWS</h3>
          <% if @bookings.empty? %>
            <div>
              <h2>There are no upcoming shows</h2>
            </div>
          <% else %>
            <% @bookings.each do |booking| %>
              <div class="card shadow">

                <p><strong>Playing at:</strong></p>
                <p><%= booking.venue.name %></p>
                <p><%= booking.venue.address %></p>

              <% if booking.start_date != booking.end_date %>
                 <h3><%= booking.start_date.strftime('%d-%m-%Y') %> - <%= booking.end_date.strftime('%d-%m-%Y') %></h3>
              <% else %>
              <h3><%= booking.start_date.strftime('%d-%m-%Y') %></h3>
              <% end  %>

              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="current-banner">
  <div class="reused-banner-inner">
    <h1>My Bookings:</h1>
    <hr>
    <% if @bookings.empty? %>
      <h3>You have no upcoming bookings!</h3>
    <% else %>
      <h3>You have <%= @bookings.count %> upcoming bookings</h3>
    <% end %>
  </div>
</div>
<div class="container">



  <% if @bookings.empty? %>
    <div class="text-center">
    <h2>You don't have any bookings <i class="fa-regular fa-face-frown-open"></i></h2>
    <hr>
    <%= link_to "Browse Listings", bands_path, class: 'btn btn-primary' %>
    </div>
  <% else %>
   <div class="cards-booking">
    <% @bookings.each do |booking| %>

      <div class="card shadow">
        <%= link_to band_path(booking.band) do %>
           <div> <%= image_tag booking.band.image_url, class: 'bookings-image' %></div>
          <% end %>
         <div class="card-inner">
        <h3><%= booking.band.name %></h3>
        <p>Booking:</p>
        <p><%= booking.start_date.strftime('%d-%m-%Y') %> - <%= booking.end_date.strftime('%d-%m-%Y') %></p>
        <p><strong>Playing at:</strong></p>
        <p><%= booking.venue.name %></p>
        <p><%= booking.venue.address %></p>
        <p><strong>Total Price:</strong> £<%= booking.total_price %></p>
        <div>
        <%= button_to "Cancel Booking", booking_path(booking), method: :delete, class: 'btn btn-danger' %>
        </div>
        </div>
      </div>
    <% end %>
  <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BANDJob</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>



    <% javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_avatar.html.erb
<%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", class: "avatar", alt: "avatar" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar-large", alt: "avatar-large" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-bordered", alt: "avatar-bordered" %>
<%= image_tag "https://kitt.lewagon.com/placeholder/users/krokrob", class: "avatar-square", alt: "avatar-square" %>

app/views/shared/_banner.html.erb
<div class="banner-hp z-0 position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.cartridgepeople.com/info/application/files/1316/1478/7917/downloadable_music_gig_crowd_thumbnail.png);">
  <div class="container">

  <div class="row justify-content-center z-1 position-relative">
    <div class="col-sm-8 position-absolute top-100 start-50 translate-middle">
    <%= form_with url: bands_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Enter Artist or Genre of music"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
    <% end %>
    </div>
    </div>

    <div class="position-relative" style="margin-top:100px">

    <h1> Putting <strong>music</strong> within <strong>your grasp </strong></h1>
    <p>Find and book bands in your local area</p>

    <div class="mt-50">
    <%= link_to "Explore", bands_path, class: "btn btn-outline-light" %>

  </div>

    </div>


  </div>


</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
        <p>Copyright &copy; BandJob</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-bandjob.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Current Listings", bands_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "My Bookings", user_bookings_path(current_user), class: "nav-link" %>
            </li>
          <% end %>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>